
- name: app set-up
  ansible.builtin.import_role:
        name: common
        tasks_from: app-setup.yaml


# - name: systemd setup
#   ansible.builtin.import_role:
#         name: common
#         tasks_from: systemd.yaml

- name: systemd setup
  ansible.builtin.import_role:
        name: common
        tasks_from: systemd.yaml


- name: go install
  ansible.builtin.import_role:
        name: common
        tasks_from: golang.yaml
         